# Generated by Django 5.2.7 on 2025-11-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='quiz',
            new_name='code',
        ),
    ]
