# Generated by Django 5.2.7 on 2025-11-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_rename_quiz_attempt_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='code',
            new_name='quiz',
        ),
    ]
